# Generated by Django 4.1.7 on 2023-03-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_status_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_status',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
