# Generated by Django 4.1.7 on 2023-03-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_id',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
