# Generated by Django 4.1.7 on 2023-03-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_created_at_order_shipment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipment_id',
            field=models.IntegerField(default=1),
        ),
    ]
