# Generated by Django 4.1.7 on 2023-03-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('uname', models.CharField(max_length=250)),
                ('product_id', models.CharField(max_length=250)),
                ('product_name', models.CharField(max_length=250)),
            ],
        ),
    ]
