# Generated by Django 4.1.7 on 2023-03-29 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship_status', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='transaction_id',
        ),
    ]
