# Generated by Django 4.1.7 on 2023-03-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship_status', '0002_remove_shipment_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order_id',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='product_id',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='total',
            field=models.FloatField(default=1),
        ),
    ]
