# Generated by Django 4.1.7 on 2023-03-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ship_status', '0003_shipment_created_at_shipment_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='order_id',
            field=models.IntegerField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='product_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
